import { TechCardModel } from '../shared/tech-card';

export const PROGRAMMING_LANGUAGES: TechCardModel[] = [
  {
    id: 'javascript',
    name: 'JavaScript',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
    color: '#F7DF1E',
    description: 'Dynamic programming language for web development',
    badges: ['Node.js', 'Express', 'React'],
    versions: ['ES2023', 'ES2022', 'ES2021', 'ES2020'],
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
    color: '#3178C6',
    description: 'Typed superset of JavaScript',
    badges: ['Type Safety', 'Modern JS', 'IntelliSense'],
    versions: ['5.3', '5.2', '5.1', '5.0', '4.9'],
  },
  {
    id: 'python',
    name: 'Python',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
    color: '#3776AB',
    description: 'Versatile language with rich ecosystem',
    badges: ['Flask', 'Django', 'FastAPI'],
    versions: ['3.12', '3.11', '3.10', '3.9', '3.8'],
  },
  {
    id: 'java',
    name: 'Java',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg',
    color: '#007396',
    description: 'Robust enterprise-grade language',
    badges: ['Spring Boot', 'Jakarta EE', 'Quarkus'],
    versions: ['21 (LTS)', '17 (LTS)', '11 (LTS)', '8 (LTS)'],
  },
  {
    id: 'csharp',
    name: 'C#',
    icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg',
    color: '#512BD4',
    description: 'Modern object-oriented programming language',
    badges: ['ASP.NET Core', 'Entity Framework', 'Blazor'],
    versions: ['12.0', '11.0', '10.0', '9.0', '8.0'],
  },
];

export const LANGUAGE_FRAMEWORKS: { [key: string]: TechCardModel[] } = {
  javascript: [
    {
      id: 'nodejs',
      name: 'Node.js',
      icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
      color: '#68a063',
      description: 'JavaScript runtime for server-side applications',
      badges: ['Express', 'NestJS', 'Fastify'],
      versions: ['20.x', '18.x (LTS)', '16.x', '14.x'],
    },
  ],
  typescript: [
    {
      id: 'nestjs',
      name: 'NestJS',
      icon: 'https://icon.icepanel.io/Technology/svg/Nest.js.svg',
      color: '#E0234E',
      description: 'Progressive Node.js framework built with TypeScript',
      badges: ['TypeScript', 'Decorators', 'Modular'],
      versions: ['10.x', '9.x', '8.x'],
    },
    {
      id: 'express',
      name: 'Express',
      icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg',
      color: '#68a063',
      description: 'Fast, unopinionated, minimalist web framework',
      badges: ['Node.js', 'typescript', 'Minimalist'],
      versions: ['4.x', '3.x', '2.x'],
    },
  ],
  python: [
    {
      id: 'django',
      name: 'Django',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/Django.png',
      color: '#092E20',
      description: 'High-level Python web framework',
      badges: ['Batteries-included', 'ORM', 'Admin'],
      versions: ['5.0', '4.2 (LTS)', '3.2 (LTS)'],
    },
    {
      id: 'flask',
      name: 'Flask',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/Flask.png',
      color: '#000000',
      description: 'Lightweight WSGI web application framework',
      badges: ['Microframework', 'Extensible', 'Simple'],
      versions: ['2.3.x', '2.2.x', '2.0.x'],
    },
    {
      id: 'fastapi',
      name: 'FastAPI',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/FastAPI.png',
      color: '#009688',
      description: 'Modern, fast web framework for building APIs',
      badges: ['High Performance', 'Type Hints', 'OpenAPI'],
      versions: ['0.100.x', '0.95.x', '0.90.x'],
    },
  ],
  java: [
    {
      id: 'spring',
      name: 'Spring Boot',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/Spring.png',
      color: '#6DB33F',
      description: 'Java-based framework for microservices',
      badges: ['Enterprise', 'Dependency Injection', 'Opinionated'],
      versions: ['3.2', '3.1', '3.0', '2.7 (LTS)'],
    },
  ],
  csharp: [
    {
      id: 'aspnet',
      name: 'ASP.NET Core',
      icon: 'https://dotnet.microsoft.com/blob-assets/images/dotnet-icons/square.png',
      color: '#512BD4',
      description: 'Cross-platform framework for building web apps',
      badges: ['Cross-platform', 'High Performance', 'Cloud-ready'],
      versions: ['8.0', '7.0', '6.0 (LTS)'],
    },
  ],
};

export const FRAMEWORK_API_TYPES: { [key: string]: TechCardModel[] } = {
  nodejs: [
    {
      id: 'rest',
      name: 'REST API',
      icon: 'https://www.opc-router.de/wp-content/uploads/2020/05/REST_socialmedia.jpg',
      description: 'Standard HTTP-based API architecture',
      color: '#4CAF50',
      badges: ['HTTP', 'Resource-based', 'CRUD'],
      versions: ['OpenAPI 3.1', 'OpenAPI 3.0'],
    },
    {
      id: 'graphql',
      name: 'GraphQL',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/GraphQL.png',
      description: 'Query language for your API',
      color: '#E10098',
      badges: ['Schema', 'Query/Mutation', 'Single Endpoint'],
      versions: ['v16.x', 'v15.x'],
    },
  ],
  express: [
    {
      id: 'rest',
      name: 'REST API',
      icon: 'https://www.opc-router.de/wp-content/uploads/2020/05/REST_socialmedia.jpg',
      description: 'Standard HTTP-based API architecture',
      color: '#4CAF50',
      badges: ['HTTP', 'Resource-based', 'CRUD'],
      versions: ['OpenAPI 3.1', 'OpenAPI 3.0'],
    },
    {
      id: 'graphql',
      name: 'GraphQL',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/GraphQL.png',
      description: 'Query language for your API',
      color: '#E10098',
      badges: ['Schema', 'Query/Mutation', 'Single Endpoint'],
      versions: ['v16.x', 'v15.x'],
    },
  ],
  nestjs: [
    {
      id: 'rest',
      name: 'REST API',
      icon: 'https://www.opc-router.de/wp-content/uploads/2020/05/REST_socialmedia.jpg',
      description: 'Standard HTTP-based API architecture',
      color: '#4CAF50',
      badges: ['HTTP', 'Resource-based', 'CRUD'],
      versions: ['OpenAPI 3.1', 'OpenAPI 3.0'],
    },
    {
      id: 'graphql',
      name: 'GraphQL',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/GraphQL.png',
      description: 'Query language for your API',
      color: '#E10098',
      badges: ['Schema', 'Query/Mutation', 'Single Endpoint'],
      versions: ['v16.x', 'v15.x'],
    },
    {
      id: 'grpc',
      name: 'gRPC',
      icon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrQZ7-LJwZI5r0oFtiqFABAfjyqw8bLmwV3g&s',
      description: 'High-performance RPC framework',
      color: '#244c5a',
      badges: ['Protocol Buffers', 'HTTP/2', 'Streaming'],
      versions: ['v1.60', 'v1.59'],
    },
  ],
  django: [
    {
      id: 'rest',
      name: 'Django REST Framework',
      icon: 'https://www.django-rest-framework.org/img/logo.png',
      description: 'Powerful toolkit for building Web APIs',
      color: '#A30000',
      badges: ['Serializers', 'ViewSets', 'Authentication'],
      versions: ['3.14.x', '3.13.x'],
    },
  ],
  flask: [
    {
      id: 'rest',
      name: 'Flask-RESTful',
      icon: 'https://flask-restful.readthedocs.io/en/latest/_static/flask-restful-small.png',
      description: 'Extension for Flask REST APIs',
      color: '#000000',
      badges: ['Resource Classes', 'Request Parsing'],
      versions: ['0.3.x', '0.2.x'],
    },
  ],
  fastapi: [
    {
      id: 'rest',
      name: 'REST API',
      icon: 'https://www.opc-router.de/wp-content/uploads/2020/05/REST_socialmedia.jpg',
      description: 'Built-in REST API support',
      color: '#4CAF50',
      badges: ['Auto Documentation', 'Pydantic', 'Type Hints'],
      versions: ['OpenAPI 3.1', 'OpenAPI 3.0'],
    },
    {
      id: 'websocket',
      name: 'WebSockets',
      icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/WebSocket_colored_logo.svg/1200px-WebSocket_colored_logo.svg.png',
      description: 'Built-in WebSocket support',
      color: '#FF6B35',
      badges: ['Async', 'Real-time', 'Built-in'],
      versions: ['Native'],
    },
  ],
  spring: [
    {
      id: 'rest',
      name: 'Spring Web MVC',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/Spring.png',
      description: 'Spring framework for building REST APIs',
      color: '#6DB33F',
      badges: ['Annotations', 'MVC', 'RESTful'],
      versions: ['6.x', '5.x'],
    },
  ],
  aspnet: [
    {
      id: 'rest',
      name: 'Web API',
      icon: 'https://dotnet.microsoft.com/blob-assets/images/dotnet-icons/square.png',
      description: 'ASP.NET Core Web API',
      color: '#512BD4',
      badges: ['Controllers', 'Model Binding', 'OpenAPI'],
      versions: ['8.0', '7.0', '6.0'],
    },
  ],
};

export const FRAMEWORK_SPECIFIC_ORMS: { [key: string]: TechCardModel[] } = {
  nodejs: [
    {
      id: 'prisma',
      name: 'Prisma',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/Prisma.png',
      description: 'Next-generation ORM',
      color: '#5A67D8',
      badges: ['Type-safe', 'Auto-migration', 'Multi-database'],
      versions: ['5.x', '4.x'],
    },
    {
      id: 'typeorm',
      name: 'TypeORM',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/TypeORM.png',
      description: 'TypeScript ORM for any database',
      color: '#FE0A5A',
      badges: ['TypeScript', 'Multi-database', 'Decorators'],
      versions: ['0.3.x', '0.2.x'],
    },
  ],
  express: [
    {
      id: 'sequelize',
      name: 'Sequelize',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/Sequelize.png',
      description: 'Promise-based Node.js ORM',
      color: '#000000',
      badges: ['Node.js', 'JavaScript', 'ORM'],
      versions: ['6.x', '5.x'],
    },
    {
      id: 'mongoose',
      name: 'Mongoose',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/Mongoose.png',
      description: 'Mongoose is a MongoDB object modeling for Node.js',
      color: '#3A495D',
      badges: ['Node.js', 'MongoDB', 'ODM'],
      versions: ['7.x', '6.x'],
    },
  ],
  nestjs: [
    {
      id: 'typeorm',
      name: 'TypeORM',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/TypeORM.png',
      description: 'TypeScript ORM for any database',
      color: '#FE0A5A',
      badges: ['TypeScript', 'Multi-database', 'Decorators'],
      versions: ['0.3.x', '0.2.x'],
    },
    {
      id: 'prisma',
      name: 'Prisma',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/Prisma.png',
      description: 'Next-generation ORM',
      color: '#5A67D8',
      badges: ['Type-safe', 'Auto-migration', 'Multi-database'],
      versions: ['5.x', '4.x'],
    },
  ],

  django: [
    {
      id: 'django-orm',
      name: 'Django ORM',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/Django.png',
      description: 'Built-in ORM for Django',
      color: '#092E20',
      badges: ['Integrated', 'Model-based', 'Admin'],
      versions: ['5.0', '4.2'],
    },
  ],
  flask: [
    {
      id: 'sqlalchemy',
      name: 'SQLAlchemy',
      icon: 'https://icon.icepanel.io/Technology/svg/SQLAlchemy.svg',
      description: 'SQL toolkit and ORM',
      color: '#D71F00',
      badges: ['Pythonic', 'Powerful', 'Flexible'],
      versions: ['2.0', '1.4'],
    },
  ],
  fastapi: [
    {
      id: 'sqlalchemy',
      name: 'SQLAlchemy',
      icon: 'https://icon.icepanel.io/Technology/svg/SQLAlchemy.svg',
      description: 'SQL toolkit and ORM',
      color: '#D71F00',
      badges: ['Pythonic', 'Powerful', 'Flexible'],
      versions: ['2.0', '1.4'],
    },
  ],
  spring: [
    {
      id: 'spring-data',
      name: 'Spring Data JPA',
      icon: 'https://icon.icepanel.io/Technology/png-shadow-512/Spring.png',
      description: 'Repository abstraction for JPA',
      color: '#6DB33F',
      badges: ['Spring', 'Repository', 'JPA'],
      versions: ['3.2', '3.1'],
    },
  ],
  aspnet: [
    {
      id: 'ef-core',
      name: 'Entity Framework Core',
      icon: 'https://dotnet.microsoft.com/blob-assets/images/dotnet-icons/square.png',
      description: 'Modern ORM for .NET',
      color: '#512BD4',
      badges: ['Code-first', 'Database-first', 'LINQ'],
      versions: ['8.0', '7.0'],
    },
  ],
};
